spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"
accounts:
  message: "this is accounts microservice"
  contactDetails:
    name: "K NISHANTH"
    email: "nishanth@gmail.com"
  onContactSupport:
    - +918019135761
    - +919989069668