spring:
  config:
    activate:
      on-profile:
        - "qa"
build:
  version: "1.2"
cards:
  message: "This is Cards Microservice in Quality Assurance environment"
  contactDetails:
    name: "K Sree Navya"
    email: "navya@gmail.com"
  onContactSupport:
    - +918019135761
    
