spring:
  config:
    activate:
      on-profile:
        - "prod"
build:
  version: "1.1"
loans:
  message: "this is Loans microservice in Production level"
  contactDetails:
    name: "K Sree Navya"
    email: "karranavyan2@gmail.com"
  onContactSupport:
    - +918019135761
    - +919989069668
